# Generated by Django 3.1.7 on 2021-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postPreview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
