# Generated by Django 3.1.7 on 2021-03-18 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_post_postpreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postPreview',
        ),
    ]
